"use client";

import { motion } from "framer-motion";
import { MapPin } from "lucide-react";

export default function ItineraryCard({ plan, onReset }: { plan: any, onReset: () => void }) {
  if (!plan || !plan.itinerary) return null;

  return (
    <div className="w-full max-w-3xl mx-auto z-10 max-h-[85vh] overflow-y-auto overflow-x-hidden p-2 custom-scrollbar">
      <div className="bg-white/10 backdrop-blur-2xl border border-white/20 p-6 md:p-8 rounded-[2rem] shadow-2xl text-white">
        <div className="flex justify-between items-start mb-2">
          <h2 className="text-3xl md:text-4xl font-extrabold tracking-tight">Your Trip to {plan.destination}</h2>
          <button 
            onClick={onReset}
            className="text-sm bg-white/10 hover:bg-white/20 px-4 py-2 rounded-full transition-colors border border-white/10"
          >
            Start Over
          </button>
        </div>
        <p className="text-emerald-300 font-medium mb-8 text-lg">{plan.days} Days Itinerary Generated by AI</p>
        
        <div className="space-y-6 md:space-y-8">
          {plan.itinerary.map((day: any, i: number) => (
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.15, duration: 0.5 }}
              key={i} 
              className="bg-slate-900/60 border border-slate-700/50 rounded-2xl p-5 md:p-6"
            >
              <div className="flex flex-col md:flex-row md:items-center justify-between border-b border-slate-700/50 pb-4 mb-4">
                <h3 className="text-2xl font-bold bg-gradient-to-r from-emerald-400 to-indigo-400 bg-clip-text text-transparent">
                  Day {day.day}
                </h3>
                <span className="text-slate-300 font-medium mt-1 md:mt-0">{day.theme}</span>
              </div>
              
              <div className="space-y-5">
                {day.places.map((place: any, j: number) => (
                  <div key={j} className="flex gap-4 group">
                    <div className="mt-1 flex-shrink-0">
                      <div className="w-8 h-8 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 flex items-center justify-center group-hover:scale-110 group-hover:bg-emerald-500/20 transition-all">
                        <MapPin size={16} />
                      </div>
                    </div>
                    <div>
                      <h4 className="text-lg font-semibold text-slate-100 group-hover:text-emerald-300 transition-colors">{place.name}</h4>
                      <p className="text-slate-400 text-sm mt-1 leading-relaxed">{place.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </div>
  );
}
